---
title: "Labnotes on CP analysis"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---


```{r startup}

library(tidyverse)
library(readxl)
library(rcdk)
library(enviPat)

data("isotopes")
data("adducts")

Cl_adducts <- readxl::read_xlsx("./data/CP_adducts.xlsx") %>%
        mutate(Formula_add = as.character(Formula_add))

adducts <- adducts %>% bind_rows(Cl_adducts)

#library(iterpc)
#library(IsoSpecR)

```



Manually generate theoretical CP homologs
```{r}

# Initiate boundaries for carbon and chlorine atoms
C <- as.integer(9:30)
Cl <- as.integer(3:30)


CP <- crossing(C, Cl) %>% #set combinations of C and Cl
        filter(C >= Cl) %>% # filter so Cl dont exceed C atoms
        filter(Cl < 15) %>% # limit chlorination level CHECK WITH LCCPs!!
        mutate(H = 2*C+2-Cl) %>% # add H atoms
        mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>% #add chemical formula
        select(Formula, C, H, Cl) # move Formula to first column

# check chem_forms
 if (any(check_chemform(isotopes = isotopes, chemforms = CP$Formula)$warning == TRUE)) {print("Warning: incorrect formula")} else {"All correct"}


# Generate fragments M-Cl and M-HCl for each homolog formula

CP_lossCl <- CP %>%
        mutate(Parent = Formula) %>%
        mutate(Fragment = "M-Cl") %>%
        mutate(Cl = Cl-1) %>%
        mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>%
        select(Parent, Fragment, Formula, C, H, Cl)


CP_lossHCl <- CP %>%
        mutate(Parent = Formula) %>%
        mutate(Fragment = "M-HCl") %>%
        mutate(Cl = Cl-1) %>%
        mutate(H = H-1) %>%
        mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>%
        select(Parent, Fragment, Formula, C, H, Cl)


# function to get isotopic patterns for all CPs. Limit the threshold to 1%, neutral form. data("isotopes") needs to be loaded first
getisotopes <- function(x) {enviPat::isopattern(isotopes = isotopes, chemforms = x, threshold = 1, plotit = FALSE, charge = -1)}

# get formula names. NOT USED
formula_names <- function(data, C12, C13, H1, H2, Cl35, Cl37) {
        data %>%
                mutate(isotope = paste0("[12C]", {{C12}}, "[13C]", {{C13}}, "[1H]", {{H1}}, "[2H]", {{H2}}, "[35Cl]", {{Cl35}}, "[37Cl]", {{Cl37}}))
}

# All formula for M-Cl
CP_lossCl_ls <- list()
for (i in seq_along(CP_lossCl$Formula)) {
        Formula <- CP_lossCl$Formula[i]
        Parent <- CP_lossCl$Parent[i]
        dat <- getisotopes(CP_lossCl$Formula[i])
        dat <- as.data.frame(dat[[1]])
        dat <- dat %>% 
                mutate(Isotope_Formula = paste0("[12C]", `12C`, "[13C]", `13C`, "[1H]", `1H`, "[2H]", `2H`, "[35Cl]", `35Cl`, "[37Cl]", `37Cl`)) %>%
                mutate(Parent_Formula = Parent) %>%
                mutate(Frag_Formula =  Formula) %>%
                mutate(Isotope = case_when(
                        `13C` + `37Cl`*2 == 0 ~ "",
                        `13C` + `37Cl`*2 == 1 ~ "+1",
                        `13C` + `37Cl`*2 == 2 ~ "+2",
                        `13C` + `37Cl`*2 == 3 ~ "+3",
                        `13C` + `37Cl`*2 == 4 ~ "+4",
                        `13C` + `37Cl`*2 == 5 ~ "+5",
                        `13C` + `37Cl`*2 == 6 ~ "+6",
                        `13C` + `37Cl`*2 == 7 ~ "+7",
                        `13C` + `37Cl`*2 == 8 ~ "+8",
                        `13C` + `37Cl`*2 == 9 ~ "+9",
                        `13C` + `37Cl`*2 == 10 ~ "+10",
                        `13C` + `37Cl`*2 == 11 ~ "+11",
                        `13C` + `37Cl`*2 == 12 ~ "+12",
                        `13C` + `37Cl`*2 == 13 ~ "+13",
                        `13C` + `37Cl`*2 == 14 ~ "+14",
                        `13C` + `37Cl`*2 == 15 ~ "+15",
                        `13C` + `37Cl`*2 == 16 ~ "+16",
                        `13C` + `37Cl`*2 == 17 ~ "+17",
                        `13C` + `37Cl`*2 == 18 ~ "+18",
                        `13C` + `37Cl`*2 == 19 ~ "+19",
                        `13C` + `37Cl`*2 == 20 ~ "+20")) %>%
                mutate(Fragment = paste0("M-Cl", Isotope)) %>%
                select(Parent_Formula, Fragment, Frag_Formula, Isotope, Isotope_Formula, `m/z`, abundance, `12C`, `13C`, `1H`, `2H`, `35Cl`, `37Cl`)
        CP_lossCl_ls[[i]] <- dat
}

CP_lossCl_ls <- do.call(rbind, CP_lossCl_ls)

# All formula for M-HCl
CP_lossHCl_ls <- list()
for (i in seq_along(CP_lossHCl$Formula)) {
        Formula <- CP_lossHCl$Formula[i]
        Parent <- CP_lossHCl$Parent[i]
        dat <- getisotopes(CP_lossHCl$Formula[i])
        dat <- as.data.frame(dat[[1]])
        dat <- dat %>% 
                mutate(Isotope_Formula = paste0("[12C]", `12C`, "[13C]", `13C`, "[1H]", `1H`, "[2H]", `2H`, "[35Cl]", `35Cl`, "[37Cl]", `37Cl`)) %>%
                mutate(Parent_Formula = Parent) %>%
                mutate(Frag_Formula =  Formula) %>%
                mutate(Isotope = case_when(
                        `13C` + `37Cl`*2 == 0 ~ "",
                        `13C` + `37Cl`*2 == 1 ~ "+1",
                        `13C` + `37Cl`*2 == 2 ~ "+2",
                        `13C` + `37Cl`*2 == 3 ~ "+3",
                        `13C` + `37Cl`*2 == 4 ~ "+4",
                        `13C` + `37Cl`*2 == 5 ~ "+5",
                        `13C` + `37Cl`*2 == 6 ~ "+6",
                        `13C` + `37Cl`*2 == 7 ~ "+7",
                        `13C` + `37Cl`*2 == 8 ~ "+8",
                        `13C` + `37Cl`*2 == 9 ~ "+9",
                        `13C` + `37Cl`*2 == 10 ~ "+10",
                        `13C` + `37Cl`*2 == 11 ~ "+11",
                        `13C` + `37Cl`*2 == 12 ~ "+12",
                        `13C` + `37Cl`*2 == 13 ~ "+13",
                        `13C` + `37Cl`*2 == 14 ~ "+14",
                        `13C` + `37Cl`*2 == 15 ~ "+15",
                        `13C` + `37Cl`*2 == 16 ~ "+16",
                        `13C` + `37Cl`*2 == 17 ~ "+17",
                        `13C` + `37Cl`*2 == 18 ~ "+18",
                        `13C` + `37Cl`*2 == 19 ~ "+19",
                        `13C` + `37Cl`*2 == 20 ~ "+20")) %>%
                mutate(Fragment = paste0("M-HCl", Isotope)) %>%
                select(Parent_Formula, Fragment, Frag_Formula, Isotope, Isotope_Formula, `m/z`, abundance, `12C`, `13C`, `1H`, `2H`, `35Cl`, `37Cl`)
        CP_lossHCl_ls[[i]] <- dat
}
CP_lossHCl_ls <- do.call(rbind, CP_lossHCl_ls)

# combine both M-Cl and M-HCl
CP_allions <- rbind(CP_lossCl_ls, CP_lossHCl_ls)

# write to excel
writexl::write_xlsx(x = CP_allions, path = paste0("./data/CP_allions_", Sys.Date(),".xlsx"))



```


Test to shinyapp
```{r testShiny}

# Initiate boundaries for carbon and chlorine atoms
C <- as.integer(9:30)
Cl <- as.integer(3:30)

# params for isopattern
threshold <- 10

# First test single adduct
adduct_ions <- c("[CP-Cl]-")

adduct_ions <- c("[CP-HCl]-", "[CO-Cl]-")

# test to convert string to vector
adduct_ions <- "[CP-HCl]-,[CO-Cl]-"
adduct_ions <- str_extract()

ion_modes <- str_extract(adduct_ions, "(?<=\\]).*") # lookbehind assertion to extract ion mode
        fragment_ions <- str_extract(adduct_ions, "(?<=.{3}).+?(?=\\])") # extract after the 2nd character and before ]
        group <- str_extract(adduct_ions, "[^\\[].{1}") # positive lookbehind for [)

# What to do with multiple fragment ions such as [CP-2H+Cl]-



# function to get adducts or fragments
getAdduct <- function(adduct_ions) {
        
        ion_modes <- str_extract(adduct_ions, "(?<=\\]).*") # lookbehind assertion to extract ion mode
        fragment_ions <- str_extract(adduct_ions, "(?<=.{3}).+?(?=\\])") # extract after the 2nd character and before ]
        group <- str_extract(adduct_ions, "[^\\[].{1}") # positive lookbehind for [)
        
        if (group == "CP") {
        data <- crossing(C, Cl) %>% #set combinations of C and Cl
        filter(C >= Cl) %>% # filter so Cl dont exceed C atoms
        filter(Cl < 15) %>% # limit chlorination level CHECK WITH LCCPs!!
        mutate(H = 2*C+2-Cl) %>% # add H atoms
        mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>% #add chemical formula
        select(Formula, C, H, Cl) # move Formula to first column
        } else if (group == "CO") {
        data <- crossing(C, Cl) %>% #set combinations of C and Cl
        filter(C >= Cl) %>% # filter so Cl dont exceed C atoms
        filter(Cl < 15) %>% # limit chlorination level CHECK WITH LCCPs!!
        mutate(H = 2*C-Cl) %>% # add H atoms
        mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>% #add chemical formula
        select(Formula, C, H, Cl) # move Formula to first column
        }  else {
                print("Input not correct, only CP or CO is allowed")
        }
        
        # check chem_forms
        # if (any(check_chemform(isotopes = isotopes, chemforms = data$Formula)$warning == TRUE)) {print("Warning: incorrect formula")} else {"All correct"}
        
        # adding ion modes to the data frame to be inserted to isopattern
        if (ion_modes == "-") {
                data <- data %>%
                        mutate(Charge = as.integer(-1))
        }else if (ion_modes == "+") {
                data <- data %>%
                        mutate(Charge = as.integer(1))
        }
        
        # generate input data for envipat based on fragment_ions
              
        if (fragment_ions == "-Cl") { # Generate fragments M-Cl for each homolog formula  
                data <- data %>%
                mutate(Parent = Formula) %>% 
                mutate(Fragment = adduct_ions) %>%
                mutate(Cl = Cl-1) %>%
                mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>%
                select(Parent, Charge, Fragment, Formula, C, H, Cl)
        } else if (fragment_ions == "-HCl") { # Generate fragments M-HCl for each homolog formula
                data <- data %>%
                mutate(Parent = Formula) %>% 
                mutate(Fragment = adduct_ions) %>%
                mutate(Cl = Cl-1) %>%
                mutate(H = H-1) %>%
                mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>%
                select(Parent, Charge, Fragment, Formula, C, H, Cl)
        } else if (fragment_ions == "+Cl") { # Generate fragments M+Cl for each homolog formula
                data <- data %>%
                mutate(Parent = Formula) %>% 
                mutate(Fragment = adduct_ions) %>%
                mutate(Cl = Cl+1) %>%
                mutate(Formula = paste0("C", C, "H", H, "Cl", Cl)) %>%
                select(Parent, Charge, Fragment, Formula, C, H, Cl)
        }

# All formula for M-Cl
CP_allions <- list()
data_ls <- list()


# function to get isotopic patterns for all CPs. Limit the threshold to 10%, neutral form. data("isotopes") needs to be loaded first
getisotopes <- function(x) {enviPat::isopattern(isotopes = isotopes, chemforms = x, threshold = 10, plotit = FALSE, charge = Charge)}

for (j in seq_along(data$Formula)) {
        Formula <- data$Formula[j]
        Parent <- data$Parent[j]
        Charge <- data$Charge[j]
        dat <- getisotopes(x = data$Formula[j])
        dat <- as.data.frame(dat[[1]])
        dat <- dat %>% 
                mutate(Isotope_Formula = paste0("[12C]", `12C`, "[13C]", `13C`, "[1H]", `1H`, "[2H]", `2H`, "[35Cl]", `35Cl`, "[37Cl]", `37Cl`)) %>%
                mutate(Parent_Formula = Parent) %>%
                mutate(Frag_Formula =  Formula) %>%
                mutate(Charge = Charge) %>%
                mutate(Isotope = case_when(
                        `13C` + `37Cl`*2 == 0 ~ "",
                        `13C` + `37Cl`*2 == 1 ~ "+1",
                        `13C` + `37Cl`*2 == 2 ~ "+2",
                        `13C` + `37Cl`*2 == 3 ~ "+3",
                        `13C` + `37Cl`*2 == 4 ~ "+4",
                        `13C` + `37Cl`*2 == 5 ~ "+5",
                        `13C` + `37Cl`*2 == 6 ~ "+6",
                        `13C` + `37Cl`*2 == 7 ~ "+7",
                        `13C` + `37Cl`*2 == 8 ~ "+8",
                        `13C` + `37Cl`*2 == 9 ~ "+9",
                        `13C` + `37Cl`*2 == 10 ~ "+10",
                        `13C` + `37Cl`*2 == 11 ~ "+11",
                        `13C` + `37Cl`*2 == 12 ~ "+12",
                        `13C` + `37Cl`*2 == 13 ~ "+13",
                        `13C` + `37Cl`*2 == 14 ~ "+14",
                        `13C` + `37Cl`*2 == 15 ~ "+15",
                        `13C` + `37Cl`*2 == 16 ~ "+16",
                        `13C` + `37Cl`*2 == 17 ~ "+17",
                        `13C` + `37Cl`*2 == 18 ~ "+18",
                        `13C` + `37Cl`*2 == 19 ~ "+19",
                        `13C` + `37Cl`*2 == 20 ~ "+20")) %>%
                mutate(Fragment = paste0(adduct_ions, Isotope)) %>%
                select(Parent_Formula, Charge, Fragment, Frag_Formula, Isotope, Isotope_Formula, `m/z`, abundance, `12C`, `13C`, `1H`, `2H`, `35Cl`, `37Cl`)
        data_ls[[j]] <- dat
}

# combine all elements in list list to get dataframe
data_ls <- do.call(rbind, data_ls)


# combine both all adduct ions
CP_allions <- rbind(CP_allions, data_ls)
return(CP_allions)

}

CP_allions_compl <- list()
for (i in seq_along(adduct_ions)) {
        input <- getAdduct(adduct_ions = adduct_ions[i])
        CP_allions_compl <- rbind(CP_allions_compl, input)
        
}

# write to excel
#writexl::write_xlsx(x = CP_allions, path = paste0("./data/CP_allions_", Sys.Date(),".xlsx"))

```


# Optimization of GC-ECNI-orbitrap-HRAMS for CPs

For SCCPs: the different electron energies and CI gas shows that the optimum parameters are: 70 eV with 1.5 ml/min methane gas. According to Thermo technical 

```{r, echo=FALSE}

gasvsev <- read_xlsx("D:/Projects/Formas_CPs_indoor/Experimental/2021/20210802_ECNI_optimization_params.xlsx", 
                     sheet = "CIgas_vs_Area") %>%
        mutate(Cigas = as.factor(Cigas), eV = as.factor(eV)) %>%
        pivot_longer(cols = where(is.numeric), names_to = "Congener_group", values_to = "Area")

gasvsev %>%
        ggplot(aes(x = Congener_group, y = Area)) +
        geom_bar(aes(fill = eV), stat = "identity", position=position_dodge()) +
        facet_grid(~Cigas, labeller = label_both) +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 90))
        


```


Calibration of 5 ppm SCCPs

```{r, echo=FALSE}

sccp <- read_xlsx("D:/Projects/Formas_CPs_indoor/Experimental/2021/20210802_ECNI_optimization_params.xlsx", 
                     sheet = "20210803_cal5ppm") %>%
        mutate(perc_Cl = as.factor(perc_Cl)) %>%
        pivot_longer(cols = C10Cl5:C13Cl9, names_to = "Congener_group", values_to = "Area")

sccp %>%
        ggplot(aes(x = Congener_group, y = Area)) +
        geom_bar(aes(fill = Congener_group), stat = "identity", position=position_dodge()) +
        facet_grid(~perc_Cl, labeller = label_both) +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 90))
        


```






