---
output: html_document
editor_options: 
  chunk_output_type: console
---

#---START----Test params for Skyline----START---------- 

```{r}

library(shiny)
library(shinythemes)
library(DT)
library(tidyverse)
library(readxl)
library(plotly)
library(crosstalk)
library(enviPat)
library(markdown)

data("isotopes")
source("./R/getAdduct.R")
source("./R/getSkyline.R")


Cmin <- 10
Cmax  <- 30
Clmin <- 5
Clmax <- 10
Adduct <- "[PCA+Cl]-"
threshold <- 50
MSresolution <- 60000

C <- as.integer(Cmin:Cmax)
Cl <- as.integer(Clmin:Clmax)
selectedAdducts <- Adduct
Adducts <- as.character(selectedAdducts)
i <- 1
adduct_ions = Adducts[i]






```


First tab
```{r}


# function to get adducts or fragment
CP_allions <- list()
for (i in seq_along(Adducts)) {
        input <- getAdduct(adduct_ions = Adducts[i], C = C, Cl = Cl, threshold = threshold)
        CP_allions <- rbind(CP_allions, input)
        }
CP_allions_glob <- CP_allions


```


Skyline tab
```{r}



                
# function to get Skyline adducts or fragments
CP_allions_sky <- list()
for (i in seq_along(Adducts)) {
        input <- getSkyline(adduct_ions = Adducts[i], C = C, Cl = Cl, threshold = threshold)
        CP_allions_sky <- rbind(CP_allions, input)
        }
CP_allions_skyline  <- CP_allions_sky


#                if(input$skylineoutput == "IonFormula"){
                CP_allions_skyline <- CP_allions_skyline %>%
                        mutate(`Molecule List Name` = case_when(str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ paste0("CP-C", `12C`),
                                                                str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ paste0("CO-C", `12C`))) %>%
                        rename(`Molecule Name` = Parent_Formula) %>%
                        mutate(`Molecular Formula` = case_when(
                                `37Cl` == 0 ~ paste0("C", `12C`, "H", `1H`, "Cl", `35Cl`),
                                `37Cl` > 0 ~ paste0("C", `12C`, "H", `1H`, "Cl", `35Cl`, "Cl'", `37Cl`)
                        )) %>%
                        mutate(`Precursor Adduct` = str_replace(Adduct, "\\].*", "]")) %>% 
                        mutate(`Precursor Adduct` = str_replace(`Precursor Adduct`, "(.+?(?=\\-))|(.+?(?=\\+))", "[M")) %>%
                        rename(`Precursor Charge` = Charge) %>%
                        add_column(`Explicit Retention Time` = NA) %>%
                        add_column(`Explicit Retention Time Window` = NA) %>%
                        group_by(`Molecule Name`) |> 
                        mutate(`Label Type` = ifelse(Rel_ab == 100, "Quan", "Qual")) |> # choose the highest rel_ab ion as quan ion and the rest will be qual
                        ungroup() |> 
                        mutate(Note = case_when(
                                `12C` < 10 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "vSCCP",
                                `12C` < 10 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "vSCCO",
                                `12C` >= 10 & `12C` < 14 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "SCCPs",
                                `12C` >= 10 & `12C` < 14 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "SCCOs",
                                `12C` >= 14 & `12C` < 18 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "MCCPs",
                                `12C` >= 14 & `12C` < 18 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "MCCOs",
                                `12C` >= 18 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "LCCPs",
                                `12C` >= 18 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "LCCOs")) %>%
                        select(`Molecule List Name`, 
                               `Molecule Name`, 
                               `Molecular Formula`, 
                               `Precursor Adduct`, 
                               `Precursor Charge`,
                               `Label Type`,
                               `Explicit Retention Time`, 
                               `Explicit Retention Time Window`, 
                               Note)
                
                
                

                
#input$skylineoutput == "Masses"){
                        
                        CP_allions_skyline2 <- CP_allions_glob %>%
                                mutate(`Molecule List Name` = case_when(str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ paste0("CP-C", `12C`),
                                                                        str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ paste0("CO-C", `12C`))) %>%
                                rename(`Molecule Name` = Parent_Formula) %>%
                                mutate(`Precursor m/z` = `m/z`) %>% 
                                mutate(`Precursor Adduct` = str_replace(Adduct, "\\].*", "]")) %>% 
                                mutate(`Precursor Adduct` = str_replace(`Precursor Adduct`, "(.+?(?=\\-))|(.+?(?=\\+))", "[M")) %>%
                                rename(`Precursor Charge` = Charge) %>%
                                #mutate(`Label Type` = paste0("M", Isotopologue)) %>%
                                add_column(`Explicit Retention Time` = NA) %>%
                                add_column(`Explicit Retention Time Window` = NA) %>%
                                group_by(`Molecule Name`) |> 
                                mutate(`Label Type` = ifelse(Rel_ab == 100, "Quan", "Qual")) |> # choose the highest rel_ab ion as quan ion and the rest will be qual
                                ungroup() %>%
                                mutate(Note = case_when(
                                        `12C` < 10 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "vSCCP",
                                        `12C` < 10 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "vSCCO",
                                        `12C` >= 10 & `12C` < 14 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "SCCPs",
                                        `12C` >= 10 & `12C` < 14 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "SCCOs",
                                        `12C` >= 14 & `12C` < 18 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "MCCPs",
                                        `12C` >= 14 & `12C` < 18 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "MCCOs",
                                        `12C` >= 18 & str_detect(Adduct, "(?<=.)CP(?=.)") == TRUE ~ "LCCPs",
                                        `12C` >= 18 & str_detect(Adduct, "(?<=.)CO(?=.)") == TRUE ~ "LCCOs")) %>%
                                select(`Molecule List Name`, 
                                       `Molecule Name`, 
                                       `Precursor Adduct`,
                                       `Precursor Charge`, 
                                       `Label Type`,
                                       `Precursor m/z` = `m/z`,
                                       `Explicit Retention Time`, 
                                       `Explicit Retention Time Window`, 
                                       Note)
                        
                        
                        output$Table3 <- DT::renderDT(server=FALSE,{ #need to keep server = FALSE otherwise excel download the visible rows of the table, but this will also give warning about large tables
                                # Show data
                                DT::datatable(CP_allions_skyline2, 
                                              filter = "top", extensions = c("Buttons", "Scroller"),
                                              options = list(scrollY = 650,
                                                             scrollX = 500,
                                                             deferRender = TRUE,
                                                             scroller = TRUE,
                                                             buttons = list(list(extend = "excel", filename = "Skyline_transition_list", title = NULL,
                                                                                 exportOptions = list(
                                                                                         modifier = list(page = "all")
                                                                                 )),
                                                                            list(extend = "csv", filename = "Skyline_transition_list", title = NULL,
                                                                                 exportOptions = list(
                                                                                         modifier = list(page = "all")
                                                                                 )),
                                                                            list(extend = "colvis", targets = 0, visible = FALSE)),
                                                             dom = "lBfrtip",
                                                             fixedColumns = TRUE), 
                                              rownames = FALSE)
                        })

                        
                



```


test bromochloroalkanes
```{r}

library(shiny)
library(shinythemes)
library(DT)
library(tidyverse)
library(readxl)
library(plotly)
library(crosstalk)
library(enviPat)
library(markdown)

data("isotopes")
source("./R/getAdduct.R")
source("./R/getSkyline.R")


Cmin <- 10
Cmax  <- 30
Clmin <- 5
Clmax <- 10
Brmin <- 1
Brmax <- 5
Adduct <- "[BCA+Cl]-"
threshold <- 50
MSresolution <- 60000

C <- as.integer(Cmin:Cmax)
Cl <- as.integer(Clmin:Clmax)
Br <- as.integer(Brmin:Brmax)
selectedAdducts <- Adduct
Adducts <- as.character(selectedAdducts)
i <- 1
adduct_ions = Adducts[i]


```



      